# Travis CI (http://travis-ci.org/) is a continuous integration
# service for open source projects. This file configures it
# to run unit tests for docli.

language: go

go:
    - 1.9
    - 1.11

matrix:
    fast_finish: true

install:
    - go get -d -v ./... && go build -v ./...

