# Travis CI (http://travis-ci.org/) is a continuous integration
# service for open source projects. This file configures it
# to run unit tests for docli.

language: go

env:
  - GO111MODULE=on

go:
    - 1.12

matrix:
    fast_finish: true

before_install:
    - go get github.com/DATA-DOG/godog/cmd/godog

install:
    - go get -d -v ./... && go build -v ./...

script:
  - test -z "$(go fmt ./...)"
  - cd pkg/args/     && godog -f progress
  - cd ../docstring/ && godog -f progress